### ISSUE TITLE
Support status badge on platform that supports it.

### ISSUE THREAD

**Issue by emilpriver** [emilpriver/jamstack-preview-and-deployments#1]
Be able to show status badges on platform that supports it.

ex: https://docs.netlify.com/monitor-sites/status-badges/

**Comment by lqze** [comment]
You might want to look at https://wordpress.org/plugins/deploy-netlifypress/ regarding button support.

**Comment by emilpriver** [comment]
@lqze Yes, I Will look into it. Atm is it not many JAMstack providers that support badge ex except Netlify
