### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by emilpriver** [emilpriver/jamstack-preview-and-deployments#23]
Add a documentation for plugin so it is easier to work with the plugin.

### Should include stuffs:
- How to implement preview with frameworks
- How the plugin works and what parameter it sends to the user.

**Comment by SmartyP** [comment]
There is a link in the readme to the following documentation, but it gives a 404 - does it need to be made public..?
https://emilpriver.github.io/jamstack-preview-and-deployments
