### ISSUE TITLE
Should this plugin still work? Installation does not change preview url.

### ISSUE THREAD

**Issue by dnspnjrs** [emilpriver/jamstack-preview-and-deployments#27]
Ive been searching for such a thing for quite some time. But im wondering if it still works? I've installed the plugin and filled out the settings accordingly. The preview URL does not change on posts / custom post types. 

Thanks!

**Comment by emilpriver** [comment]
Hello, have u checked that preview is enabled for the post type ? Could you send a screenshot of your settings?`Dont forget to hide secrets!

**Comment by dnspnjrs** [comment]
> Hello, have u checked that preview is enabled for the post type ? Could you send a screenshot of your settings?`Dont forget to hide secrets!

Thanks for your message!

Ill clarify:
- I have a clean setup of nextjs / wordpress 5.8.1 with 1 custom post type
- In wordpress "custom post type" settings the option "revisions" is enabled
- Preview URL and Preview "secret" are added

Expected result: Plugin adds id, secret and postType to the preview url.

View attached screenshots for details. Plugin doesn't add the url on custom post type or a page.

Settings page:
![Screenshot 2021-11-09 at 08 55 55](https://user-images.githubusercontent.com/6238828/140885603-b10f4523-232f-454d-9a45-5d501e5501ae.png)

When hovering Custom post type:
![Screenshot 2021-11-09 at 08 57 05](https://user-images.githubusercontent.com/6238828/140885575-ae78a77a-46c2-45d2-b84f-547d72190138.png)

**Comment by dnspnjrs** [comment]
Allright

> > Hello, have u checked that preview is enabled for the post type ? Could you send a screenshot of your settings?`Dont forget to hide secrets!
> 
> Thanks for your message!
> 
> Ill clarify:
> 
> * I have a clean setup of nextjs / wordpress 5.8.1 with 1 custom post type
> * In wordpress "custom post type" settings the option "revisions" is enabled
> * Preview URL and Preview "secret" are added
> 
> Expected result: Plugin adds id, secret and postType to the preview url.
> 

Allright, I see that the plugin doesn't take in account a different "Site Address". When I changed the "Wordpress Address" to match the "Site Address" the plugin works for previewing posts.

The only issue now is that GraphQL doesn't query unpublished posts. Is there a way you found a solution around this?

**Comment by emilpriver** [comment]
Hello, You need to handle the preview function yourself.  Have you built an endpoint to handle the preview call? We use GraphQL with WordPress at work and the difference is that we tell GraphQL to show us a preview post or a "revision" as WordPress calls it. I recommend you looking at the examples made by next.js with Wordpress or this page: https://nextjs.org/docs/advanced-features/preview-mode. This issue show how the query `asPreview` which you use to get preview data. 

Closeing issue as problem is not with the plugin
